### ISSUE TITLE
Facing a problem while explore with other language 

### ISSUE THREAD

**Issue by Arulmurugan-Sivapoosam** [k-lpmg/Tagging#1]
When i explore with **Tamil** (SouthIndian language) as tagging suggestion then the tagging attribute is not applied for a whole word.

**Solution:** 

**taggingAttributeRange** should be like this **NSMakeRange(model.range.location+1, model.text.utf16.count)**. 

need to get the characters count from **utf16** encoding. 

it'll be good if apply the same for **updateAttributeText** method's **selectedLocation** param (For cursor placing). 

Refer the screenShots.

![flaw](https://user-images.githubusercontent.com/46676192/52326358-63930900-2a0e-11e9-9b26-5a9ea7d31acf.png)
![fix](https://user-images.githubusercontent.com/46676192/52326360-668df980-2a0e-11e9-9ff2-c8bd0c95664e.png)

**Comment by k-lpmg** [comment]
Thanks! @Arulmurugan-Sivapoosam 
I will check and update soon.

**Comment by k-lpmg** [comment]
Hi @Arulmurugan-Sivapoosam 
I fix this issue and release 0.4.0 with support swift 4.2.
Thanks!

**Comment by Arulmurugan-Sivapoosam** [comment]
Hi @k-lpmg 
Thanks for the update. will try with the new version.
