### ISSUE TITLE
Add textview delegate but tagging datasource not call

### ISSUE THREAD

**Issue by paneaktae** [k-lpmg/Tagging#6]
How to fix ? thx u

**Comment by k-lpmg** [comment]
Hi @paneaktae 
sorry for delay answer.

You need to configure below code.

### Code
``` swift
tagging.dataSource = self
```

### Example URL
https://github.com/k-lpmg/Tagging/blob/54285049602bc46be0708454f647e9a368f45a85/Example/Sources/TaggingViewController.swift#L41
